spegel:
  appendMirrors: true
  containerdSock: /run/containerd/containerd.sock
  containerRegistryConfigPath: /etc/cri/conf.d/hosts
service:
  registry:
    hostPort: 29999
serviceMonitor:
  enabled: true
