apiVersion: ENC[AES256_GCM,data:hbM=,iv:12dn5K0PILFrodCaOX/55/DynJfi8w+ahNlnxXc71uE=,tag:IakSRfvq6bQqsQcAnnWWsg==,type:str]
kind: ENC[AES256_GCM,data:/KPFsN36,iv:7svKniJWzNPjgQcXim6133dR/c5V09DxLH5J5wohBtM=,tag:9UD8uqmh/ctErNStuKp7dA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Iw/OZlVxRF8rb/W55SyZ,iv:bn4i3cqmhFO8alx+lnKRtpis5sN5/RAXNQsmbfOElXo=,tag:svLDn4vHepQ58ezOP21gKw==,type:str]
    namespace: ENC[AES256_GCM,data:9Llp2RUnNhJcPso=,iv:C725PnlRCVh2sYZO72BIH0t+k7WZ/bq5bqht0FN6rHI=,tag:UomC2QCuDPHK/Y3bthscmQ==,type:str]
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:fzSGFCN4EKmoxL2NHPL4O6b9jwVxZakTGLErtdzQkiwZCdlQZD+RSQ==,iv:Caelaf3a66LseDseGrOgodFXro5SzNpPailJFOD2V3s=,tag:pAbP6fP+V4jJlI5wBPnAnw==,type:str]
    UNIFI_HOST: ENC[AES256_GCM,data:UA+D7TAhBuJZcrtbNMa/RsCYzEeAMMfTbw==,iv:5SZhvjPVrBOJVkY1VdBdiSv9uGpDMf7RuzEFx8DrNJY=,tag:/JFBgeo+wizBc5xolSxRXg==,type:str]
    UNIFI_USER: ENC[AES256_GCM,data:wR4VvSBmodeNcs90,iv:t2JQUn6u9MA1NstuXe/M8C+xrwfKoNaT8PveCnBU4nM=,tag:wJnHObfGQo/iD10q0MvFvw==,type:str]
    UNIFI_PASS: ENC[AES256_GCM,data:yuPq0Abf3tiakn3gsALvE+MRuBZa5LQ=,iv:ejUe+F1FLtSjo/3awB94Lcc+l83fw13wBIDkQYGjUGE=,tag:ksDrUA1kZP7MzCoVsn4HKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qex5ky044eyqrsymkg6ynfvpy96wxjdldvdmlmy35e5mt2v5zczqla98ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Ym8yS2s4a2hWRVAyYnhT
            RWdQM1I3MjQ5eUtMRDIxUjQ1VkhFM1JyeWhBCnZnTGRFKy9FbnIvUnlwTXptSnBz
            WitRbmZycDRuMENLVnVFeWNsMHp5ajAKLS0tIGhYTXpEcGhWV2JFa28rQWdZMW1R
            NFF5dVpPN2hBdXBDakJQUTFjb09pMVEKyFazXcEPma1eWezXxcSkA8hrJR1tG0CJ
            Fhh6h/YwI/PJJAqOL5KlPGSIpOpUdIb7nsWpzZkBulVNQiOACFlc2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18lt2qwmtvuj0ujf9zrxr4wsehhxuvqc3e79s53c20wq5fv6jhqyst4m83t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV3NOU3VnL3BHSEd6MXkv
            TGFBeFNuVUtDRDdnSmZaVnBYbDdCZ1dlRUYwCmNkWlF6LzBJUVhOMEkrRGVlemtl
            a0NodFBuSkR1dGorbEQ5QStiUWdHT2MKLS0tIHhhT081S1JSUlEwdUhDRXhWRmEz
            ekdrVm0yN1U2Q3R5dmV6d2lSNWtVVE0KE02CmuP3zUpcU2dFlOpVuDE5wS6WlIx8
            7oA9SPErYABQeLiMgWrniJy+NGjW20Qsl2Eq5Fw0Qpt0G2k04V/6Tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vz6akhdt4hwfxe3d2n7er2nym7lttcg7uchafysajdtwa696zcyq6latjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVDZmSUtnOUJOMVVsRXQr
            S05XWlpVeUMzSW9QTStKOEFQeHk5Z3d3T1VZClRmem5iemlhbDMrd2JEOWNZWEVk
            SmM5RWNibWdUSUt0OGZoNXJESndmbzQKLS0tIDdQMVdId0NEdnN5NHErUUdJU3pj
            MUIyaTJqZVp1aFVqbTVyZ2QrdFhXbXcKxmoNW68sHSW7swKj+ljdCv+GX0R0cBvi
            8cUr4nr1vJ9D/jVOje0K3HaV7EtWqtaMvhqtPX+364/aGmW8kwBayA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T01:22:26Z"
    mac: ENC[AES256_GCM,data:pfVqGpPl75e00V/0zpjkKEFvOl09R26g4aA0JZrFbVsyvEEDrNWY0tOExLo/YJYYXEzGA0QTLMfCXRtTi9P/GOzM+4AEvQ18ehdjN1kCneiAgP8/Gi8bAjSzEdo525yfLB0IUXyMWOsnMz8wdYOtwwRj6rqfyq9DFj6+px7xXRE=,iv:3xLpM/fgvnzwiAaCk7m93yWtqMeLCAXlttOcMQF/5bQ=,tag:rbcsBiIW8udkLLLAOVZYXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
