apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:VaFFfx1lmscYXXgwmvf+4idP/uHVKIXnZTrveiV3TWS+QsA0G/6UaQ==,iv:et7RyYTzuWFtpr6cvAu9BCL+qK04RUwaD035MkIqu8A=,tag:VRvdaPhx42r/zeXDEK/6KA==,type:str]
    UNIFI_HOST: ENC[AES256_GCM,data:1XyBaJxuHapqScTtr4n6nXxCS6WgEQ6CiQ==,iv:df3lO1yP5uOHGINfg5a2YdUYpsJ3uHsrWBgTrv1U4qM=,tag:f38QF6Hnvo6aPJqoqcjUCQ==,type:str]
    UNIFI_USER: ENC[AES256_GCM,data:PO+YxaLqQCjLRTPy,iv:RYQre0zfcitTgeqInl3Y+hf4YXg4YTHt5Th2a6sf9n8=,tag:VCx9QkYao/0VS0kxyfjSsA==,type:str]
    UNIFI_PASS: ENC[AES256_GCM,data:YOMsUniln+DMxHnZQ8Q0DFfS0Pi4FbU=,iv:cQ8BZLWblmeCMX0p1PzDUoEQxiqm9sbDuM6Lk08z2Sk=,tag:RzA9I1O9B1YaXLD7mGmvMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xltxc87jgp6fzjlwapfctpa23vaqn2cqwqyta8vh0g0yrgs6adfqs0arc9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMUc1OVo3MmdBNG1SV0lm
            NFJVRzh3RVl1Unk1TExGaGZlVDNiVzFWZldnCmE4SnMvZWVmSkRySGpQUGQwUHgw
            WnFJMU1RN09obmNIejJmalhvZzc3b2sKLS0tIHVQQ0N5azkxZ3AwN3lNSlhmTkp2
            QU1JdCtvWUp3ZDdBaWdSU2xGQ1c4OHcKvxKfENodmkQgFK4NGO9aC86J6Z7kTKus
            jc/Se4btP6dSLgYvJgSnCIAcf8ws+fgDeWnqrWfkmTCmqMz0QZ9sGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18lt2qwmtvuj0ujf9zrxr4wsehhxuvqc3e79s53c20wq5fv6jhqyst4m83t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MmhJTHFZc1RRZlgyNG8w
            S2VyTzFEcUpYMU53N09ua05QdzVGVVpUQWlBCnhqT00wb0JranBOMXBNUXNxSWJF
            SFREQ1BVdFZmelFEdEE5UVF3M0V6SEEKLS0tIE5Sd0JqdmFMYURkZ0I1bnM2enYw
            aFRtVG1pZE93K09qODVnNlhISTZZeVkKX5wSN6BDtojafYZb94XXfNs48i4qUArG
            cK/KT7BVKR+B6A9hRhGHuvbf8m9RyJzfN2JEYQ0oVjksLQ85Q1sNKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T07:04:25Z"
    mac: ENC[AES256_GCM,data:LBmnTfXKuYz4DF9WXoNn1FDrodGBxV2jH2glBoIIHJFUu4zzhk8qDL6Xx+gJdCFGTM/o5O5efcMwPCzsqXl82d6TsUorCfQ+BNlwg3999NUGfqrxwkwO+MA/v0Gday7+70K6sjt2X04p11Bto3Y3k19UlQoUoJMd8lw4WebKloY=,iv:a8Dxd1OLzI6Qje7vBA7e8SrE7T8c+aGcbJC1fMwLSc8=,tag:nlCuPno0GK4HCJFfyXXwjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
