---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname metrics-server
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: ./apps/kube-system/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-git
  wait: true
