---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-external
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-external-dns
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    fullnameOverride: &name externaldns-external
    domainFilters:
      - rocinante.lan
    env: []
    extraArgs:
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=external-nginx
  postRenderers:
    - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: *name
          patch: |
            - op: add
              path: /spec/template/spec/enableServiceLinks
              value: false
