---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname prometheus-operator-crds
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: ./apps/monitoring/prometheus-operator/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-git
  wait: false
