keys:
  - &pnby_mm_age age1qex5ky044eyqrsymkg6ynfvpy96wxjdldvdmlmy35e5mt2v5zczqla98ed
  - &roci_mm_age age18lt2qwmtvuj0ujf9zrxr4wsehhxuvqc3e79s53c20wq5fv6jhqyst4m83t
  - &vdrm_mm_age age1vz6akhdt4hwfxe3d2n7er2nym7lttcg7uchafysajdtwa696zcyq6latjk
creation_rules:
  - path_regex: .*/talos/.*\sops.ya?ml$
    keygroups:
      - age:
          - *pnby_mm_age
          - *roci_mm_age
          - *vdrm_mm_age
  - path_regex: .*\.sops.ya?ml$
    key_groups:
      - pgp: []
        age:
          - *pnby_mm_age
          - *roci_mm_age
          - *vdrm_mm_age
