# https://numtide.github.io/devshell

[[env]]
name = "KUBECONFIG"
eval = "$PRJ_ROOT/main/kubeconfig"

[[env]]
name = "TALOSCONFIG"
eval = "$PRJ_ROOT/main/bootstrap/talos/clusterconfig/talosconfig"

[[commands]]
package = "pkgs.go-task"
name = "task"

[[commands]]
package = "unstable.kubectl"
category = "kubernetes"

[[commands]]
package = "unstable.talosctl"
category = "talos"

[[commands]]
package = "pkgs.talhelper"
category = "talos"

[[commands]]
package = "unstable.fluxcd"
category = "kubernetes"

[[commands]]
package = "unstable.kubernetes-helm-wrapped"
category = "kubernetes"

[[commands]]
package = "unstable.helmfile-wrapped"
category = "kubernetes"

[[commands]]
package = "unstable.cilium-cli"
category = "kubernetes"

[devshell]
packages = [
  "unstable.treefmt",
  "pkgs.mdformat",
  "pkgs.nixpkgs-fmt",
  "pkgs.taplo",
  "unstable.yamlfmt",
  "pkgs.pre-commit",
  "pkgs.pre-commit-hook-ensure-sops",
  "pkgs.jq",
  "pkgs.yq",
]
