---
version: "3"
vars:
  CLUSTER: cluster
env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  TALOSCONFIG: "{{.ROOT_DIR}}/bootstrap/talos/clusterconfig/talosconfig"
includes:
  bootstrap:
    aliases:
      - b
    dir: .taskfiles/bootstrap
    taskfile: .taskfiles/bootstrap
  flux:
    aliases:
      - f
    dir: .taskfiles/flux
    taskfile: .taskfiles/flux
  k8s:
    aliases:
      - k
    dir: .taskfiles/k8s
    taskfile: .taskfiles/k8s
  sops:
    aliases:
      - s
    dir: .taskfiles/sops
    taskfile: .taskfiles/sops
  talos:
    aliases:
      - t
    dir: .taskfiles/talos
    taskfile: .taskfiles/talos
tasks:
  default:
    silent: true
    cmds:
      - task -l
  format:
    desc: Format files with Treefmt
    aliases:
      - f
      - fmt
    cmds:
      - treefmt -u info
