# https://github.com/numtide/treefmt

[global]
excludes = ["*.sops.*"]

[formatter.mdformat]
command = "mdformat"
includes = ["*.md"]

[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.taplo]
command = "taplo"
includes = [".*toml"]
options = ["format"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
