---
version: "3"
vars:
  APP_PATH: "{{.ROOT_DIR}}/apps"
tasks:
  ks-*:
    desc: Perform an action on a Flux KS [PATH=required] [NAME] [SRC]
    preconditions:
      - test -f {{.APP_PATH}}/{{.PATH}}/ks.yaml
      - which flux kubectl yq
    requires:
      vars:
        - PATH
    vars:
      OPERATION: "{{index .MATCH 0}}"
      KS:
        sh: flux --namespace flux-system get kustomizations {{base .PATH}} 2>&1
    cmd: >
      flux build --namespace flux-system ks {{if .NAME}}{{.NAME}}{{else}}{{base .PATH}}{{end}} --kustomization-file {{.APP_PATH}}/{{.PATH}}/ks.yaml --path {{.APP_PATH}}/{{.PATH}}{{-if .SRC}}/{{.SRC}}{{end}} {{if contains "not found" .KS}}--dry-run \{{end}} | yq 'with(select(.apiVersion == "kustomize.toolkit.fluxcd.io/v1" and .kind == "Kustomization"); .metadta.namespace = "flux-system")' | kubectl {{.OPERATION}} {{if eq .OPERATION "apply"}}--server-side --field-manager=kustomize-controller{{end}} --filename -
