---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-git
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: https://github.com/ModestMeowth/cluster.git
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./main/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: cluster-git
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
