---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-sigs-external-dns
  namespace: flux-system
spec:
  interval: 30m
  timeout: 3m
  url: https://kubernetes-sigs.github.io/external-dns
