apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postfinance
  namespace: flux-system
spec:
  interval: 30m
  timeout: 3m
  url: https://postfinance.github.io/kubelet-csr-approver
