apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  interval: 30m
  chart:
    spec:
      chart: k8tz
      version: 0.17.1
      interval: 30m
  values:
    namespace: system-controllers
    replicaCount: 2
    timezone: America/Chicago
    cronJobTimeZone: true
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: k8tz
            topologyKey: kubernetes.io/hostname
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Namespace
            patch: |-
              $patch: delete
              apiVersion: v1
              kind: Namespace
              metadata:
                name: not-used
