---
clusterName: &clustername cluster
endpoint: https://192.168.100.101:6443

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: 1.8.3
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.31.3

additionalApiServerCertSans: &sans
  - rocinante.cat-alkaline.ts.net
  - &vip ${clusterEndpointIP}
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: controller
    ignoreHostname: true
    ipAddress: 192.168.100.101, 192.168.100.102, 192.168.100.103
    installDisk: /dev/vda
    controlPlane: true
    networkInterfaces:
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - driver: virtio_net
              physical: true
        dhcp: true
        vip:
          ip: *vip

controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clustername
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=1
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
  patches:
    # Configure containerd
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false
    # Disable search domain everywhere
    - |-
      machine:
        network:
          disableSearchDomain: true
    # Enable cluster discovery
    - |-
      cluster:
        discovery:
          enabled: true
          registries:
            kubernetes:
              disabled: false
            service:
              disabled: false
    # Disable host DNS
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
    # Configure Kubelet
    - |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 150
          extraMounts: []
          nodeIP:
            validSubnets:
              - 192.168.100.0/24
    # Enable KubePrism
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
    # Configure cluster
    - |-
      cluster:
        allowSchedulingOnMasters: true
        coreDNS:
          disabled: true
        proxy:
          disabled: true
        scheduler:
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway
    # Configure static host entries
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 192.168.100.100
              aliases:
                - cluster.local
            - ip: 192.168.100.101
              aliases:
                - talos1
            - ip: 192.168.100.102
              aliases:
                - talos2
            - ip: 192.168.100.103
              aliases:
                - talos3
    # Configure custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_instances: 8192
          fs.inotify.max_user_watches: 1048576
          net.core.rmem_max: 67108864
          net.core.wmem_max: 67108864
          net.ipv4.tcp_rmem: 4096 87380 33554432
          net.ipv4.tcp_wmem: 4096 87380 33554432
          net.ipv4.tcp_tw_reuse: 1
          net.ipv4.tcp_window_scaling: 1
          net.ipv4.tcp_congestion_control: bbr
    # Configure udev rules
    - |-
      machine:
        udev:
          rules:
            # Intel GPU
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44" ,MODE="0660"
    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 192.168.100.0/24
    # Configure NFS mount options
    - |-
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nconnect=16
    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
    # Enable K8s Talos API access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
