---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname kubelet-csr-approver
  namespace: flux-system
spec:
  targetNamespace: system-controllers
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: ./main/apps/system-controllers/kubelet-csr-approver/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-git
  wait: true
