apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rocinante.lan
spec:
  secretName: rocinante-lan-tls
  issuerRef:
    name: letsencrypt-production
  commonName: rocinante.lan
  dnsNames:
    - rocinante.lan
    - "*.rocinante.lan"
